Repository mi-voz-mi-voto/mi-voz-mi-voto, pull requests merged in 2022-02, with the labels that each got.

#22 Feat/eb api post
  public/favicon.ico
  public/index.html
  pull_request_template.md
  src/App.css
  src/App.js
  src/Components/EmailNotificationForm/EmailNotificationForm.js
  src/Components/Header/Header.js
  src/Components/MainContainer/MainContainer.js
  src/apiCalls.js
  src/endpoints.js
Labels: feature, phase 01

#23 Feat/eb errors loading
  src/App.css
  src/Assets/loading.png
  src/Assets/no-voice1.png
  src/Assets/no-voice2.png
  src/Components/EmailNotificationForm/EmailNotificationForm.css
  src/Components/EmailNotificationForm/EmailNotificationForm.js
  src/Components/Error/Error.css
  src/Components/Error/Error.js
  src/Components/Loading/Loading.css
  src/Components/Loading/Loading.js
  src/apiCalls.js
  src/endpoints.js
Labels: feature, phase 01

#30 Testing/eb email notification form
  .gitignore
  cypress.json
  cypress/fixtures/errorDuplicate.json
  cypress/fixtures/states.json
  cypress/fixtures/success.json
  cypress/fixtures/user1.json
  cypress/fixtures/user2.json
  cypress/fixtures/user3.json
  cypress/integration/email-notification-form-spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Assets/fail.png
  src/Assets/success.png
  src/Components/EmailNotificationForm/EmailNotificationForm.css
  src/Components/EmailNotificationForm/EmailNotificationForm.js
  src/Components/Error/Error.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/endpoints.js
Labels: testing, phase 01

#31 Feat/main page routing component and routes
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Assets/no-voice2.png
  src/Components/ElectionProtection/ElectionProtection.css
  src/Components/ElectionProtection/ElectionProtection.js
  src/Components/EmailNotificationForm/EmailNotificationForm.css
  src/Components/Error/Error.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/HomePageRouting/HomePageRouting.css
  src/Components/HomePageRouting/HomePageRouting.js
  src/Components/Loading/Loading.js
  src/Components/MainContainer/MainContainer.css
  src/Components/MainContainer/MainContainer.js
  src/Components/RegisterToVote/RegisterToVote.css
  src/Components/RegisterToVote/RegisterToVote.js
  src/Components/RouteCard/RouteCard.css
  src/Components/RouteCard/RouteCard.js
  src/Components/VoterIdLaws/VoterIdLaws.css
  src/Components/VoterIdLaws/VoterIdLaws.js
  src/index.js
Labels: feature, phase 02

#37 Create main.yml for CI
  .github/workflows/main.yml
  cypress.json
  cypress/integration/email-notification-form-spec.js
Labels: feature, testing, phase 01

#43 Testing/eb main page
  cypress/fixtures/election-protection.json
  cypress/fixtures/routes.json
  cypress/fixtures/voter-id-laws.json
  cypress/integration/main-page-spec.js
  cypress/support/commands.js
  src/Components/Header/Header.js
  src/Components/HomePageRouting/HomePageRouting.js
  src/Components/RouteCard/RouteCard.css
  src/Components/RouteCard/RouteCard.js
  src/Components/VoterIdLaws/VoterIdLaws.js
Labels: testing, phase 02

#44 Testing/eb election protection id laws
  cypress/fixtures/electionProtection.json
  cypress/fixtures/voterIdLaws.json
  cypress/integration/election-protection-spec.js
  cypress/integration/voter-id-laws-spec.js
  public/index.html
  pull_request_template.md
  src/Components/ElectionProtection/ElectionProtection.js
  src/Components/VoterIdLaws/VoterIdLaws.js
Labels: testing, phase 02

#46 Testing/eb dev stories
  cypress/fixtures/devs.json
  cypress/integration/our-story-spec.js
  src/Components/DevStories/DevStories.js
Labels: testing, phase 02

#47 Feat/translations
  cypress/fixtures/election-protection.json
  cypress/fixtures/english.json
  cypress/fixtures/errorNotSubscribed.json
  cypress/fixtures/spanish.json
  cypress/fixtures/success.json
  cypress/fixtures/successUnsubscribe.json
  cypress/fixtures/user1.json
  cypress/fixtures/user2.json
  cypress/fixtures/user3.json
  cypress/fixtures/voter-id-laws.json
  cypress/integration/election-protection-spec.js
  cypress/integration/email-notification-form-spec.js
  cypress/integration/main-page-spec.js
  cypress/integration/our-story-spec.js
  cypress/integration/unsubscribe-form-spec.js
  cypress/integration/voter-id-laws-spec.js
  package-lock.json
  package.json
  src/Assets/devs.js
  src/Components/ElectionProtection/ElectionProtection.css
  src/Components/ElectionProtection/ElectionProtection.js
  src/Components/EmailNotificationForm/EmailNotificationForm.js
  src/Components/Error/Error.css
  src/Components/Error/Error.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/HomePageRouting/HomePageRouting.css
  src/Components/HomePageRouting/HomePageRouting.js
  src/Components/HomePageRouting/routes.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/RouteCard/RouteCard.js
  src/Components/Unsubscribe/Unsubscribe.js
  src/Components/VoterIdLaws/VoterIdLaws.css
  src/Components/VoterIdLaws/VoterIdLaws.js
  src/Components/Wrapper.js
  src/Languages/en.json
  src/Languages/es.json
  src/endpoints.js
  src/index.js
Labels: bug, feature, testing, user interface, refactor, phase 01

#53 Testing/eb unsubscribe & response object translations
  cypress/fixtures/errorDuplicateES.json
  cypress/fixtures/errorNotSubscribedES.json
  cypress/fixtures/successES.json
  cypress/fixtures/successUnsubscribeES.json
  cypress/integration/email-notification-form-spec.js
  cypress/integration/unsubscribe-form-spec.js
  src/endpoints.js
Labels: testing, refactor, phase 02

#55 Add readme title, description, demo, local setup, technologies and cr…
  README.md
Labels: documentation, phase 02

#56 Testing/eb 'success' & 'error' response object translations
  cypress/fixtures/errorDuplicate.json
  cypress/fixtures/errorDuplicateES.json
  cypress/fixtures/errorNotSubscribed.json
  cypress/fixtures/errorNotSubscribedES.json
  cypress/fixtures/successES.json
  cypress/fixtures/successUnsubscribeES.json
  cypress/integration/email-notification-form-spec.js
  cypress/integration/unsubscribe-form-spec.js
  src/Components/Error/Error.js
Labels: testing, refactor

#58 Update endpoints.js to connect to remote BE host
  cypress/integration/email-notification-form-spec.js
  cypress/integration/unsubscribe-form-spec.js
  src/Components/Error/Error.css
  src/Components/Wrapper.js
  src/apiCalls.js
  src/endpoints.js
Labels: feature

#59 Remove CORS
  src/Components/EmailNotificationForm/EmailNotificationForm.js
  src/apiCalls.js
  src/endpoints.js
Labels: bug
